package com.smartdevicelink.exception;

public enum SmartDeviceLinkExceptionCause {
	BLUETOOTH_ADAPTER_NULL,
	BLUETOOTH_DISABLED,
	INCORRECT_LIFECYCLE_MODEL,
	INVALID_ARGUMENT,
	INVALID_RPC_PARAMETER,
	PERMISSION_DENIED,
	RESERVED_CORRELATION_ID,
	SMARTDEVICELINK_CONNECTION_FAILED,
	SMARTDEVICELINK_PROXY_CYCLED,
	SMARTDEVICELINK_PROXY_DISPOSED,
	SMARTDEVICELINK_PROXY_OBSOLETE,
	SMARTDEVICELINK_REGISTRATION_ERROR,
	SMARTDEVICELINK_UNAVAILALBE,
	INVALID_HEADER;	
}
